name: koino
description: A new Flutter project.
publish_to: 'none' 
version: 2.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^1.2.0  
  cloud_firestore: ^2.2.0
  
  firebase_analytics: ^8.1.0
  firebase_auth: ^1.2.0
  
  firebase_crashlytics: ^2.0.4
  firebase_performance: ^0.7.0+3

  # google_sign_in: ^5.0.1
  email_validator: ^2.0.1
  datetime_picker_formfield: ^2.0.0
  enum_to_string: ^2.0.1
  meta: ^1.3.0
  provider: ^5.0.0
  flutter_bloc: ^7.0.0
  equatable: ^2.0.1
  font_awesome_flutter: ^9.1.0

  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true