name: koino
description: An app for christian youth-groups to organize their events.
publish_to: 'none' 
version: 2.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^1.6.0  
  cloud_firestore: ^2.5.1
  
  firebase_analytics: ^8.3.1
  firebase_auth: ^3.1.0
  
  firebase_crashlytics: ^2.2.1
  firebase_performance: ^0.7.0+9

  # google_sign_in: ^5.0.1
  email_validator: ^2.0.1
  datetime_picker_formfield: ^2.0.0
  enum_to_string: ^2.0.1
  meta: ^1.7.0
  provider: ^6.0.0
  flutter_bloc: ^7.2.0
  equatable: ^2.0.3
  font_awesome_flutter: ^9.1.0

  cupertino_icons: ^1.0.3

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true